name: fks_training
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch==2.8.0
    - torchvision==0.23.0
    - torchaudio==2.8.0
    - transformers==4.56.0
    - datasets==4.0.0
    - accelerate==1.10.1
    - wandb==0.21.2
    - scikit-learn==1.7.1
    - numpy==2.3.2
    - pandas==2.3.2
    - matplotlib==3.10.6
    - seaborn==0.13.2
    - tensorboard==2.20.0
    - optuna==4.5.0
    - mlflow==3.3.2
    - pytz
    - fastapi>=0.115.0
    - uvicorn[standard]>=0.32.0
    - pydantic>=2.9.0

